import type { Metadata } from "next";
import { Krub } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { cn } from "@/lib/utils";

import "./globals.css";

const font = Krub({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "antialiased")}>
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
