import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { cn } from "@/lib/utils";

import "../globals.css";
import { InternationalProvider } from "@/providers/international-provider";
import { getDictionary } from "@/lib/dictionaries";

// const font = Krub({
//   subsets: ["latin", "thai"],
//   weight: ["300", "400", "500", "600", "700"],
// });

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  const dictionary = await getDictionary(locale as "en" | "th");

  return (
    <html lang={locale}>
      <body className={cn(font.className, "antialiased")}>
        <InternationalProvider initialLanguage={locale as "en" | "th"} dictionary={dictionary}>
          <NuqsAdapter>
            {children}
            <Toaster position="top-center" />
          </NuqsAdapter>
        </InternationalProvider>
      </body>
    </html>
  );
}
